language: haskell
ghc:
  # - 8.0 # Currently not supported by travis
  - 7.6.3

install: 
  - cabal install --only-dependencies --enable-tests
  
script: 
  - cabal configure && cabal build && ./run_tests.sh

branches:
  only:
    - master
    - stable
